<?php

/**
 * @file
 * Provides hooks.
 */

use Drupal\commerce_cart_api\Plugin\Field\ComputedOrderTotalFieldItemList;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_field_access().
 */
function commerce_cart_api_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  $field_access = \Drupal::getContainer()->get('commerce_cart_api.field_access');
  return $field_access->handle($operation, $field_definition, $account, $items);
}

/**
 * Implements hook_entity_base_field_info().
 */
function commerce_cart_api_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'commerce_order') {
    $fields['order_total'] = BaseFieldDefinition::create('map')
      ->setLabel(t('Order total'))
      ->setReadOnly(TRUE)
      ->setComputed(TRUE)
      ->setClass(ComputedOrderTotalFieldItemList::class);
    return $fields;
  }
}
