/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, Backbone) {
  Drupal.commerceCart.CartIconView = Backbone.View.extend({
    initialize: function initialize() {},
    render: function render() {

      var template = Drupal.commerceCart.getTemplate({
        id: 'commerce_cart_js_block_icon',
        data: '<img src="<%= icon %>" alt="Cart"/>'
      });
      this.$el.html(template.render({
        icon: this.model.getIcon()
      }));
    }
  });
})(jQuery, Drupal, Backbone);