/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal, Backbone) {
  Drupal.commerceCart.CartContentsView = Backbone.View.extend({
    render: function render() {

      var template = Drupal.commerceCart.getTemplate({
        id: 'commerce_cart_js_block_contents',
        data: '<div>' + '        <% _.each(carts, function(cart) { %>' + '         <div data-cart-contents=\'<% print(JSON.stringify(cart)) %>\'></div>' + '        <% }); %>' + '</div>'
      });
      this.$el.html(template.render({
        carts: this.model.getCarts()
      }));

      this.$el.find('[data-cart-contents]').each(function () {
        var contents = new Drupal.commerceCart.CartContentsItemsView({
          el: this,
          model: Drupal.commerceCart.model
        });
        contents.render();
      });
    }
  });
})(jQuery, Drupal, Backbone);