/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, _, Drupal, drupalSettings) {
  var cache = {};

  _.templateSettings = {
    interpolate: /\{\{(.+?)\}\}/g
  };
  Drupal.commerceCart = {
    getTemplate: function getTemplate(data) {
      var id = data.id;
      if (!cache.hasOwnProperty(id)) {
        cache[id] = {
          render: _.template(data.data)
        };
      }
      return cache[id];
    }
  };

  Drupal.behaviors.cartBlock = {
    attach: function attach(context) {
      $(context).find('#commerce_cart_js_block').once('cart-block-render').each(function () {
        var model = new Drupal.commerceCart.CartBlockModel(drupalSettings.cartBlock.context);
        var view = new Drupal.commerceCart.CartBlockView({
          el: this,
          model: model
        });
        model.fetchCarts();
      });
    }
  };
})(jQuery, _, Drupal, drupalSettings);