/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Backbone, Drupal) {
  Drupal.commerceCart.CartBlockModel = Backbone.Model.extend({
    defaults: {
      icon: '',

      count: 0,

      carts: [],

      countText: {
        singular: '1 item',
        plural: '@count items'
      },

      url: '',

      links: ['<a href="' + Drupal.url('cart') + '">' + Drupal.t('View cart') + '</a>']
    },

    getUrl: function getUrl() {
      return this.get('url');
    },
    getIcon: function getIcon() {
      return this.get('icon');
    },
    getCount: function getCount() {
      return this.get('count');
    },
    getCountPlural: function getCountPlural() {
      return this.get('countText').plural;
    },
    getCountSingular: function getCountSingular() {
      return this.get('countText').singular;
    },
    getLinks: function getLinks() {
      return this.get('links');
    },
    getCarts: function getCarts() {
      return this.get('carts');
    },
    fetchCarts: function fetchCarts() {
      var _this = this;

      var data = fetch(Drupal.url('cart?_format=json'), {
        credentials: 'include'
      });
      data.then(function (res) {
        return res.json();
      }).then(function (json) {
        var count = 0;
        for (var i in json) {
          count += json[i].order_items.length;
        }
        _this.set('count', count);
        _this.set('carts', json);
        _this.trigger('cartsLoaded', _this);
      });
    }
  });
})(Backbone, Drupal);